### ISSUE TITLE
libpointpillars.so: undefined reference to `createNvOnnxParser_INTERNAL'

### ISSUE THREAD

**Issue by hufangjian** [Abraham423/CenterPointTensorRT#2]
I run  make ,get this error!

**Comment by Abraham423** [comment]
The issue might be related to TRT version, which version are you using?

**Comment by YoushaaMurhij** [comment]
I have the same error! I used the version that you mentioned in the Readme. _vTensorRT : 8.0.1.6_

**Comment by Abraham423** [comment]
Hi,
I cloned this repo and reimplemented again and found no error, I think this issue might be related to nvonnxparser.so, make sure you can link to this lib successfully .

**Comment by hufangjian** [comment]
I solve it 


target_link_libraries(centerpoint 
                         ${PCL_LIBRARIES} 
                         ${Boost_LIBRARIES} 
                         ${CUDA_LIBRARY} 
                         ${CUDA_RUNTIME_LIBRARY} 
                         pointpillars
                         pointpillarsCU
                         nvonnxparser
                         nvinfer
                         
                         ${CUDA_LIB_PATH}libcudart.so
                         
                         )

**Comment by Abraham423** [comment]
![图片](https://user-images.githubusercontent.com/25930661/149269072-d31e80cd-d4fa-40d5-ac7c-0e56a0fef853.png)

**Comment by Abraham423** [comment]
Great !
