### ISSUE TITLE
Test with ouster lidar

### ISSUE THREAD

**Issue by irmuun20** [Abraham423/CenterPointTensorRT#29]
I would like to test model on ouster lidar data. How can I set the following parameters? what is the difference between two X_MIN, and X_CENTER_MIN etc and what is X_STEP?

```
// pillar size 
#define X_STEP 0.32f
#define Y_STEP 0.32f
#define X_MIN -74.88f
#define X_MAX 74.88f
#define Y_MIN -74.88f
#define Y_MAX 74.88f
#define Z_MIN -2.0f
#define Z_MAX 4.0f

#define X_CENTER_MIN -80.0f
#define X_CENTER_MAX 80.0f
#define Y_CENTER_MIN -80.0f
#define Y_CENTER_MAX 80.0f
#define Z_CENTER_MIN -10.0f
#define Z_CENTER_MAX 10.0f

#define PI 3.141592653f
// paramerters for preprocess
#define BEV_W 468
#define BEV_H 468
#define MAX_PILLARS 32000 //20000 //32000
#define MAX_PIONT_IN_PILLARS 20
#define FEATURE_NUM 10
#define PFE_OUTPUT_DIM 64
#define THREAD_NUM 4
```

**Comment by irmuun20** [comment]
![image](https://user-images.githubusercontent.com/126429803/223597555-4b6367b5-7b5d-4e1e-b67f-057c23d7c768.png)

**Comment by irmuun20** [comment]
With ouster sample data, it is detecting trees as people.

**Comment by irmuun20** [comment]
Used ouster lidar `Signal 1` and `Signal 2` Values instead of intensity and elongation (waymo):

```
intensity = np.tanh(Signal1 / 255.0)
elongation = np.tanh(Signal2 / 255.0)
```
and got the following results: cars are detected (most of them) but people are barely being detected:
![image](https://user-images.githubusercontent.com/126429803/223902374-8e009378-eacb-491f-a181-53406f4bc3bc.png)
There is a person on the road that is very close to lidar but not being detected.

**Comment by Hale423** [comment]
X_MIN， X_MAX are used to define point cloud range in preprocess and BEV size, where $H_{BEV} = (X_{MAX} - X_{MIN})/X_{STEP}$

X_CENTER_MIN& X_CENTER_MAX define ranges  that are used when making post processing where objs out of that range  are not detected

**Comment by irmuun20** [comment]
What variables should be changed when one uses different lidar like ouster 2(128)? Thanks

**Comment by Hale423** [comment]
Hi,
I think it's due to the data difference, the model I provide is trained
from waymo dataset velodyne 64 lidar. Maybe you should train a new model
with your new dataset, and deploy it as TRT model, then run inference, in
README I provide the details on how to deploy your own model.

BW,
Hao

irmuun20 ***@***.***> 于2023年3月13日周一 08:20写道：

**Comment by irmuun20** [comment]
Thanks for the suggestion but at the moment, I don't have annotated cloud point data collected by my lidar. So, for now I will use waymo setting as default, and when I get my own data, I will train model as you suggested.

**Comment by mariamsamiiiir** [comment]
Hello , I need to know if signal2 is the refelctivitty or the range in ouster lidar because I want to map it to elongation like you have done but i don't it is which value.
Thank you
