### ISSUE TITLE
3d tracker sort

### ISSUE THREAD

**Issue by irmuun20** [Abraham423/CenterPointTensorRT#30]
Will you provide C++ implemention of 3d sort tracker? Thank you.

**Comment by irmuun20** [comment]
Why not use original waymo tracker implemented in centerpoint? https://github.com/tianweiy/CenterPoint/blob/master/tools/waymo_tracking/tracker.py

**Comment by Hale423** [comment]
I didn't implement it in C++, the tracking is only implemented offline

**Comment by irmuun20** [comment]
I see, I wonder if it is possible to convert original tracker mentioned above (by tianweiy) to c++ and use it with your code? and I wonder Why not use original waymo tracker? thanks

**Comment by Hale423** [comment]
Yes, by the time this project is pushed, the online tracking c++ code is unfinished, the python code I provided is from one of my earlier project, that's why I didn't follow waymo tracker.

**Comment by irmuun20** [comment]
I see. Thank you for your reply
