### ISSUE TITLE
About velocity

### ISSUE THREAD

**Issue by irmuun20** [Abraham423/CenterPointTensorRT#31]
Hi, I wonder how you obtain velocity in your implementation. I read the paper and it states that results from two time-steps are compared to calculate the velocity but I don't see it in your code. Thanks.
```
Paper statement: velocity estimate is special, as it requires two input map-views the current and previous time-step. It predicts
the difference in object position between the current and the past frame.
```

**Comment by irmuun20** [comment]
https://github.com/HaohaoNJU/CenterPoint/blob/7728be92e118e633602b8c2d96a5f955d03dec99/src/postprocess.cpp#L292

**Comment by Hale423** [comment]
Yes, the velocity is invalid in single-sweep model, we replace it with some other values !

**Comment by irmuun20** [comment]
I see, 
About dataset https://pan.baidu.com/s/1Ua9F3eFflA9Gckpa9U-1Eg I don't have baidu account so I couldn't download it. Would you please put it on other cloud like dropbox or google drive ?
