### ISSUE TITLE
velocity

### ISSUE THREAD

**Issue by irmuun20** [Abraham423/CenterPointTensorRT#34]
I used [waymo tracker](https://github.com/tianweiy/CenterPoint/blob/08c973a5054ac8dadae2e9dc54e9109123e8076b/tools/waymo_tracking/tracker.py) from CenterPoint, How could I obtain velocity from the model? Thanks

**Comment by Hale423** [comment]
This model doesn't support velocity detection, you need at least two sweeps pcls to to that. However you can get velos by kalman filter,  pls refer to the tracking code .

**Comment by nwdxbx** [comment]
Hi, @HaohaoNJU, when I want get the velocity,  I find the class KalmanBoxTracker of sort_3d.py file ， the kalman filter set 13 dim  quantity of state， can you tell me what does each state mean, Thanks!
