### ISSUE TITLE
Question About PointDim Waymo

### ISSUE THREAD

**Issue by mhmmdjafarg** [Abraham423/CenterPointTensorRT#38]
Hi, I'm new to point cloud processing. I want to know why is the point dim here is 5? Is it x,y,z,i and what is the 5th is it elongation? 
And do you have idea what to put in feature if the lidar dont provide elongation?

Thanks

**Comment by Hale423** [comment]
It's elongation: The elongation of the laser pulse beyond its nominal
width. Elongation in conjunction with intensity is useful for classifying
spurious objects, such as dust, fog, rain. Our experiments suggest that a
highly elongated low-intensity return is a strong indicator for a spurious
object, while low intensity alone is not a sufficient signal

see here <https://arxiv.org/pdf/1912.04838v7.pdf>

Jafar Muhammad ***@***.***> 于2023年6月15日周四 16:00写道：

**Comment by Hale423** [comment]
The 5th feature doesn't really affect the det results,  most lidars don't provide it

**Comment by mhmmdjafarg** [comment]
Okay thanks for the explanation. My lidar don't provide it, is it okay to set to 0 or what's the best way?

**Comment by Hale423** [comment]
you can export a pfe model that feeds forward 4 channel point cloud

Jafar Muhammad ***@***.***> 于2023年6月19日周一 11:19写道：

**Comment by mhmmdjafarg** [comment]
Okay thanks , but what about the preprocess part? 
```
 feature[4 +  pillarCountIdx*MAX_PIONT_IN_PILLARS * FEATURE_NUM+ pointNumInPillar* FEATURE_NUM] = points[idx*pointDim+4]; // time_lag
```

What happen if my lidar dont provide it? Should it be subtitute by other feature or how ya? Thanks
